### ISSUE TITLE
Our Bird Song MVP

### ISSUE THREAD

**Issue by HopeIvy12** [SchoolOfCode/week-3-hackathon-hohoho#1]
```[tasklist]
### Tasks
- [ ] Create the three basic file and connect them
- [ ] Make sure we can get data back: get a fetch request to check data and have a look at the object to see what is in the object. Get through postman
- [ ] Get AIP connected to our site
- [ ] create a  UI that can play a song
- [ ] Connect song input to the html
- [ ] Limit length of song
- [ ] Create UI that has a species name
- [ ] Random Index generator: list of breed name to compare to. We need to have a comparing keywords, that compares the song to the correct and incorrect breed.
```
